updates to docker-osx-dev

diff --git a/modules/docker-osx-dev b/modules/docker-osx-dev
--- a/modules/docker-osx-dev
+++ b/modules/docker-osx-dev
@@ -39,7 +39,6 @@ readonly DEFAULT_COMMAND="$SYNC_COMMAND"
 readonly BIN_DIR="/usr/local/bin"
 
 # docker host constants
-
 readonly BOOT2DOCKER_USER="docker"
 
 # docker-compose constants
@@ -49,7 +48,7 @@ readonly DEFAULT_COMPOSE_FILE="docker-compose.yml"
 readonly DEFAULT_PATHS_TO_SYNC="."
 readonly DEFAULT_EXCLUDES=".git"
 readonly DEFAULT_IGNORE_FILE=".dockerignore"
-readonly RSYNC_FLAGS="--archive --log-format 'Syncing %n: %i' --delete --omit-dir-times --inplace --whole-file"
+readonly RSYNC_FLAGS="--archive --log-format 'Syncing %n: %i' --delete --omit-dir-times --inplace --whole-file -l"
 
 # docker-osx-dev repo constants
 readonly RSYNC_BINARY_URL="https://raw.githubusercontent.com/brikis98/docker-osx-dev/master/lib/rsync"
@@ -372,14 +371,13 @@ function init_boot2docker {
     boot2docker init
   fi
 
-  check_for_shared_folders
-
   if ! is_boot2docker_running; then
     log_info "Starting Boot2Docker VM"
     boot2docker start --vbox-share=disable
   fi
 
   configure_boot2docker
+  check_for_shared_folders
 }
 
 ################################################################################
@@ -450,22 +448,16 @@ function init_docker_host {
 function install_rsync_on_docker_host {
   log_info "Installing rsync in the Docker Host image"
 
-  if $DOCKER_HOST_SSH_COMMAND "if ! type rsync > /dev/null 2>&1; then tce-load -wi rsync; fi" ; then
-    log_info "Successfully installed rsync in the Docker Host Image"
-  else
-    log_info "Failed to install rsync from existing mirror"
-    log_info "Backing up existing mirror and changing mirror to http://distro.iblibio.org/"
-    $DOCKER_HOST_SSH_COMMAND "cat /opt/tcemirror > /tmp/tcemirror.bak"
-    $DOCKER_HOST_SSH_COMMAND "echo 'http://distro.ibiblio.org/' > /opt/tcemirror"
-    if $DOCKER_HOST_SSH_COMMAND "tce-load -wi rsync" ; then
-      log_info "Successfully installed rsync from http://distro.ibiblio.org/"
-    else
-      log_info "Failed to install rsync from http://distro.ibiblio.org/"
-      log_info "Installing rsync from GitHub"
+  if ! $DOCKER_HOST_SSH_COMMAND "if ! type rsync > /dev/null 2>&1; then tce-load -wi rsync; fi"; then
+
+    # For some reason, the tce-load command often exits with an error code, even
+    # if rsync installed successfully. Therefore, re-run just the type command
+    # to see if it actually worked
+
+    if ! $DOCKER_HOST_SSH_COMMAND "type rsync > /dev/null 2>&1" ; then
+      log_info "Failed to install rsync using tce-load, falling back to install rsync from pre-built binary in docker-osx-dev GitHub repo"
       $DOCKER_HOST_SSH_COMMAND "sudo wget -P $BIN_DIR $RSYNC_BINARY_URL && sudo chmod +x $BIN_DIR/rsync"
     fi
-    log_info "Restoring original tce-load mirror"
-    $DOCKER_HOST_SSH_COMMAND "cat /tmp/tcemirror.bak > opt/tcemirror"
   fi
 }
 
@@ -630,6 +622,16 @@ function brew_install {
   else
     log_info "Installing $readable_name"
     eval "$brew_command install $package_name"
+
+    # It seems that brew install can fail to install a dependency, but exit
+    # without an error code, so the set -e flag does not help us. Example:
+    # https://github.com/brikis98/docker-osx-dev/issues/124
+    # Therefore, explicitly check that the dependency was installed before
+    # proceeding.
+    if ! type "$command_name" > /dev/null 2>&1; then
+      log_error "Failed to install dependency $readable_name. Check the log output above for reasons."
+      exit 1
+    fi
   fi
 }
 
@@ -640,7 +642,7 @@ function install_dependencies {
   log_info "Updating HomeBrew"
   brew update
 
-  brew_install "caskroom/cask/brew-cask" "Cask" "" false
+  brew_install "caskroom/cask/brew-cask" "Cask" "brew cask" false
   brew_install "boot2docker" "Boot2Docker" "boot2docker" false
   brew_install "docker-compose" "Docker Compose" "docker-compose" false
   brew_install "docker-machine" "Docker Machine" "docker-machine" false
@@ -716,7 +718,7 @@ function do_rsync {
 
     local readonly rsh_flag="--rsh=\"ssh -i $DOCKER_HOST_SSH_KEY -o IdentitiesOnly=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null\""
 
-    local readonly rsync_cmd="rsync $RSYNC_FLAGS $include_flags $exclude_flags $rsh_flag $path_to_sync $DOCKER_HOST_SSH_URL:$parent_folder"
+    local readonly rsync_cmd="rsync $RSYNC_FLAGS $include_flags $exclude_flags $rsh_flag $path_to_sync $DOCKER_HOST_SSH_URL:$parent_folder 2>&1 | grep -v \"^Warning: Permanently added\""
     log_debug "$rsync_cmd"
 
     eval "$rsync_cmd" 2>&1 | log_info
